version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: sudo apt install python3 && cp config_sample.env config.env && sudo apt-get install \apt-transport-https \ca-certificates \curl \gnupg-agent \software-properties-common && sudo docker build . -t mirror-bot && sudo docker run mirror-bot
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
