version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker: /Dockerfile
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: chmod +x start.sh 
                   ./start.sh
          name: Test

workflows:
  main:
    jobs:
      - build
