version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build: Dockerfile
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: 
          command: bash start.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
